[package]
name = "rtiow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.23"
auto_ops = "0.3.0"
num-traits = "0.2.15"