[package]
name = "rtiow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_ops = "0.3.0"
macroquad = "0.3.25"
num_cpus = "1.13.1"
num-traits = "0.2.15"
rand = "0.8.5"